---
title: Graydidi
url: https://graydidi.com
baseurl: "https://graydidi.com"
desc: Cool tunes to keep your cool in crazy times.
about: Tune in, turn on and chill out. Welcome!
image: https://graydidi.com/graydidi_headshot.jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 10
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
